apps/pages/urls.py
from django.urls import path

from apps.pages.views import *


app_name = 'pages'

urlpatterns = [
    path('', home_page_view, name='home'),
    path('error/', error_page_view, name='error'),
    path('about/', about_page_view, name='about'),
    path('contact/', contact_page_view, name='contact'),
    path('blog/', blog_list_page_view, name='blog_list'),
    path('blog/detail/', blog_detail_page_view, name='blog_detail'),
    path('products/', product_grid_view, name='product_grid'),
    path('products/detail/', product_detail_view, name='product_detail'),
    path('cart/', product_cart_view, name='cart'),
    path('checkout/', product_checkout_view, name='checkout'),
    path('login/', user_login_view, name='login'),
    path('register/', user_register_view, name='register'),
    path('reset-password/', user_reset_password_view, name='reset_password'),
    path('account/', user_account_view, name='account'),
    path('wishlist/', user_wishlist_view, name='wishlist'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.pages.urls', namespace='pages')),
    # path('', include('apps.accounts.urls', namespace='accounts')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.db import models

# Create your models here.

apps/pages/models.py
from django.db import models

apps/accounts/views.py
from django.shortcuts import render

# Create your views here.

apps/pages/views.py
from django.shortcuts import render
from django.contrib import messages


def home_page_view(request):
    return render(request, 'home3.html')


def error_page_view(request):
    return render(request, 'auth/404.html')


def about_page_view(request):
    return render(request, 'auth/about-us.html')


def contact_page_view(request):
    if request.method == 'POST':
        messages.success(request, 'Your message has been sent successfully!')
    return render(request, 'auth/contact.html')


def blog_detail_page_view(request):
    return render(request, 'blogs/blog-detail.html')


def blog_list_page_view(request):
    return render(request, 'blogs/blog-list-sidebar-left.html')


def product_grid_view(request):
    return render(request, 'products/product-grid-sidebar-left.html')


def product_detail_view(request):
    return render(request, 'products/product-detail.html')


def product_cart_view(request):
    return render(request, 'products/product-cart.html')


def product_checkout_view(request):
    return render(request, 'products/product-checkout.html')


def user_login_view(request):
    return render(request, 'user/user-login.html')


def user_register_view(request):
    return render(request, 'user/user-register.html')


def user_reset_password_view(request):
    return render(request, 'user/user-reset-password.html')


def user_account_view(request):
    return render(request, 'user/user-acount.html')


def user_wishlist_view(request):
    return render(request, 'user/user-wishlist.html')

templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Basic Page Needs -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{% block title %}Furnitica - Minimalist Furniture HTML Template{% endblock %}</title>

	<meta name="keywords" content="Furniture, Decor, Interior">
	<meta name="description" content="Furnitica - Minimalist Furniture HTML Template">
	<meta name="author" content="tivatheme">

	<!-- Mobile Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700" rel="stylesheet">

	<!-- Vendor CSS -->
	<link rel="stylesheet" href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'libs/font-awesome/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'libs/nivo-slider/css/nivo-slider.css' %}">
	<link rel="stylesheet" href="{% static 'libs/nivo-slider/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'libs/nivo-slider/css/style.css' %}">
	<link rel="stylesheet" href="{% static 'libs/font-material/css/material-design-iconic-font.min.css' %}">
	<link rel="stylesheet" href="{% static 'libs/slider-range/css/jslider.css' %}">
	<link rel="stylesheet" href="{% static 'libs/owl-carousel/assets/owl.carousel.min.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700" rel="stylesheet">

    <!-- libs CSS -->
    <link rel="stylesheet" href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/nivo-slider/css/nivo-slider.css' %}">
    <link rel="stylesheet" href="{% static 'libs/nivo-slider/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'libs/nivo-slider/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'libs/font-material/css/material-design-iconic-font.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/slider-range/css/jslider.css' %}">
    <link rel="stylesheet" href="{% static 'libs/owl-carousel/assets/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/slick-slider/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'libs/slick-slider/css/slick-theme.css' %}">

    <!-- Template CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reponsive.css' %}">

	<!-- Template CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/reponsive.css' %}">
</head>

{% block content %}{% endblock %}

</html>

templates/layout/footer.html
{% load static %}
		<!-- footer -->
		<footer class="footer-one">
			<div class="inner-footer">
				<div class="container">
					<div class="footer-top col-lg-12 col-xs-12">
						<div class=" row">
							<div class="nov-html col-lg-4 col-sm-12 col-xs-12">
								<div class="block">
									<div class="block-content">
										<p class="logo-footer">
											<img src="{% static 'img/home/logo.png' %}" alt="img">
										</p>
										<p class="content-logo">Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmod tempor incididunt
											ut labore et dolore magna aliqua. Ut enim ad minim
										</p>
									</div>
								</div>
								<div class="block">
									<div class="block-content">
										<ul>
											<li>
												<a href="#">About Us</a>
											</li>
											<li>
												<a href="#">Reasons to shop</a>
											</li>
											<li>
												<a href="#">What our customers say</a>
											</li>
											<li>
												<a href="#">Meet the teaml</a>
											</li>
											<li>
												<a href="#">Contact our buyers</a>
											</li>
										</ul>
									</div>
								</div>
								<div class="block">
									<div class="block-content">
										<p class="img-payment ">
											<img class="img-fluid" src="{% static 'img/home/payment-footer.png' %}" alt="img">
										</p>
									</div>
								</div>
							</div>
							<div class="nov-html col-lg-4 col-sm-6">
								<div class="block m-top">
									<div class="title-block">
										Contact Us
									</div>
									<div class="block-content">
										<div class="contact-us">
											<div class="title-content">
												<i class="fa fa-home" aria-hidden="true"></i>
												<span>Address :</span>
											</div>
											<div class="content-contact address-contact">
												<p>123 Suspendis matti, Visaosang Building VST District NY Accums, North American
												</p>
											</div>
										</div>
										<div class="contact-us">
											<div class="title-content">
												<i class="fa fa-envelope" aria-hidden="true"></i>
												<span>Email :</span>
											</div>
											<div class="content-contact mail-contact">
												<p>support@domain.com</p>
											</div>
										</div>
										<div class="contact-us">
											<div class="title-content">
												<i class="fa fa-phone" aria-hidden="true"></i>
												<span>Hotline :</span>
											</div>
											<div class="content-contact phone-contact">
												<p>+0012-345-67890</p>
											</div>
										</div>
										<div class="contact-us">
											<div class="title-content">
												<i class="fa fa-clock-o" aria-hidden="true"></i>
												<span>Opening Hours :</span>
											</div>
											<div class="content-contact hours-contact">
												<p>Monday - Sunday / 08.00AM- 19.00</p>
												<span>(Except Holidays)</span>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="tiva-modules col-lg-4 col-md-6">
								<div class="block m-top">
									<div class="block-content">
										<div class="title-block">Newsletter</div>
										<div class="sub-title">Sign up to our newsletter to get the latest articles, lookbooks voucher codes direct
											to your inbox
										</div>
										<div class="block-newsletter">
											<form action="#" method="post">
												<div class="input-group">
													<input type="text" class="form-control" name="email" value="" placeholder="Enter Your Email">
													<span class="input-group-btn">
														<button class="effect-btn btn btn-secondary " name="submitNewsletter" type="submit">
															<span>subscribe</span>
														</button>
													</span>
												</div>
												<input type="hidden" name="action" value="0">
											</form>
										</div>
									</div>
								</div>
								<div class="block m-top1">
									<div class="block-content">
										<div class="social-content">
											<div class="title-block">
												Follow us on
											</div>
											<div id="social-block">
												<div class="social">
													<ul class="list-inline mb-0 justify-content-end">
														<li class="list-inline-item mb-0">
															<a href="#" target="_blank">
																<i class="fa fa-facebook"></i>
															</a>
														</li>
														<li class="list-inline-item mb-0">
															<a href="#" target="_blank">
																<i class="fa fa-twitter"></i>
															</a>
														</li>
														<li class="list-inline-item mb-0">
															<a href="#" target="_blank">
																<i class="fa fa-google"></i>
															</a>
														</li>
														<li class="list-inline-item mb-0">
															<a href="#" target="_blank">
																<i class="fa fa-instagram"></i>
															</a>
														</li>
													</ul>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="block m-top1">
									<div class="block-content">
										<div class="payment-content">
											<div class="title-block">
												Payment accept
											</div>
											<div class="payment-image">
												<img class="img-fluid" src="{% static 'img/home/payment.png' %}" alt="img">
											</div>
										</div>
										<!-- Popup newsletter -->
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div id="tiva-copyright">
				<div class="container">
					<div class="row">
						<div class="text-center col-lg-12 ">
							<span>
								<a target="_blank" href="https://www.templateshub.net">Templates Hub</a>
							</span>
						</div>
					</div>
				</div>
			</div>
		</footer>

templates/layout/header-base.html
{% load static %}
<header>

			<!-- header left mobie -->
			<div class="header-mobile d-md-none">
				<div class="mobile hidden-md-up text-xs-center d-flex align-items-center justify-content-around">

					<!-- menu left -->
					<div id="mobile_mainmenu" class="item-mobile-top">
						<i class="fa fa-bars" aria-hidden="true"></i>
					</div>

					<!-- logo -->
					<div class="mobile-logo">
						<a href="index-2.html">
							<img class="logo-mobile img-fluid" src="{% static 'img/home/logo-mobie.png' %}" alt="Prestashop_Furnitica">
						</a>
					</div>

					<!-- menu right -->
					<div class="mobile-menutop" data-target="#mobile-pagemenu">
						<i class="zmdi zmdi-more"></i>
					</div>
				</div>

				<!-- search -->
				<div id="mobile_search" class="d-flex">
					<div id="mobile_search_content">
						<form method="get" action="#">

							<input type="text" name="s" value="" placeholder="Search">
							<button type="submit">
								<i class="fa fa-search"></i>
							</button>
						</form>
					</div>
					<div class="desktop_cart">
						<div class="blockcart block-cart cart-preview tiva-toggle">
							<div class="header-cart tiva-toggle-btn">
								<span class="cart-products-count">1</span>
								<i class="fa fa-shopping-cart" aria-hidden="true"></i>
							</div>
							<div class="dropdown-content">
								<div class="cart-content">
									<table>
										<tbody>
											<tr>
												<td class="product-image">
													<a href="product-detail.html">
														<img src="{% static 'img/product/5.jpg' %}" alt="Product">
													</a>
												</td>
												<td>
													<div class="product-name">
														<a href="product-detail.html">Organic Strawberry Fruits</a>
													</div>
													<div>
														2 x
														<span class="product-price">£28.98</span>
													</div>
												</td>
												<td class="action">
													<a class="remove" href="#">
														<i class="fa fa-trash-o" aria-hidden="true"></i>
													</a>
												</td>
											</tr>
											<tr class="total">
												<td colspan="2">Total:</td>
												<td>£92.96</td>
											</tr>

											<tr>
												<td colspan="3" class="d-flex justify-content-center">
													<div class="cart-button">
														<a href="product-cart.html" title="View Cart">View Cart</a>
														<a href="product-checkout.html" title="Checkout">Checkout</a>
													</div>
												</td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- header desktop -->
			<div class="header-top d-xs-none ">
				<div class="container">
					<div class="row">
						<!-- logo -->
						<div class="col-sm-2 col-md-2 d-flex align-items-center">
							<div id="logo">
								<a href="index-2.html">
									<img src="{% static 'img/home/logo.png' %}" alt="logo" class="img-fluid">
								</a>
							</div>
						</div>

						<!-- menu -->
						<div class="col-sm-5 col-md-5 align-items-center justify-content-center navbar-expand-md main-menu">
							<div class="menu navbar collapse navbar-collapse">
								<ul class="menu-top navbar-nav">
									<li>
										<a href="{% url 'pages:home' %}" class="parent">Home</a>
										{% comment %} <div class="dropdown-menu">
											<ul>
												<li class="item">
													<a href="index-2.html" title="Home Page 1">Home Page 1</a>
												</li>
												<li class="item">
													<a href="home2.html" title="Home Page 2">Home Page 2</a>
												</li>
												<li class="item">
													<a href="home3.html" title="Home Page 3">Home Page 3</a>
												</li>
												<li class="item">
													<a href="home4.html" title="Home Page 4">Home Page 4</a>
												</li>
												<li class="item">
													<a href="home5.html" title="Home Page 5">Home Page 5</a>
												</li>
											</ul>
										</div> {% endcomment %}
									</li>
									<li>
										<a href="{% url 'pages:blog_list' %}" class="parent">Blog</a>
										{% comment %} <div class="dropdown-menu">
											<ul>
												<li class="item">
													<a href="blog-list-sidebar-left.html" title="Blog List (Sidebar Left)">Blog List (Sidebar Left)</a>
												</li>
												<li class="item">
													<a href="blog-list-sidebar-left2.html" title="Blog List (Sidebar Left) 2">Blog List (Sidebar Left) 2</a>
												</li>
												<li class="item">
													<a href="blog-list-sidebar-right.html" title="Category Blog (Right column)">Blog List (Sidebar Right)</a>
												</li>
												<li class="item">
													<a href="blog-list-no-sidebar.html" title="Blog List (No Sidebar)">Blog List (No Sidebar)</a>
												</li>
												<li class="item">
													<a href="blog-grid-no-sidebar.html" title="Blog Grid (No Sidebar)">Blog Grid (No Sidebar)</a>
												</li>
												<li class="item">
													<a href="blog-detail.html" title="Blog Detail">Blog Detail</a>
												</li>
											</ul>
										</div> {% endcomment %}
									</li>
									<li class="nav-link">
										<a href="{% url 'pages:about' %}" class="parent">Page</a>
										{% comment %} <div class="dropdown-menu drop-tab">
											<ul>
												<li class="item container group">
													<div class="dropdown-menu dropdown-tab">
														<ul>
															<li class="item col-md-4 float-left">
																<span class="menu-title">Category Style</span>
																<div class="menu-content">
																	<ul class="col">
																		<li>
																			<a href="product-grid-sidebar-left.html">Product Grid (Sidebar Left)</a>
																		</li>
																		<li>
																			<a href="product-grid-sidebar-right.html">Product Grid (Sidebar Right)</a>
																		</li>
																		<li>
																			<a href="product-list-sidebar-left.html">Product List (Sidebar left) </a>
																		</li>
																	</ul>
																</div>
															</li>
															<li class="item col-md-4 html float-left">
																<span class="menu-title">Product Detail Style</span>
																<div class="menu-content">
																	<ul>
																		<li>
																			<a href="product-detail.html">Product Detail (Sidebar Left)</a>
																		</li>
																		<li>
																			<a href="#">Product Detail (Sidebar Right)</a>
																		</li>
																	</ul>
																</div>
															</li>
															<li class="item col-md-4 html float-left">
																<span class="menu-title">Bonus Page</span>
																<div class="menu-content">
																	<ul>
																		<li>
																			<a href="404.html">404 Page</a>
																		</li>
																		<li>
																			<a href="about-us.html">About Us Page</a>
																		</li>
																	</ul>
																</div>
															</li>
														</ul>
													</div>
												</li>
											</ul>
										</div> {% endcomment %}
									</li>
									<li>
										<a href="{% url 'pages:contact' %}" class="parent">Contact US</a>
									</li>
								</ul>
							</div>
						</div>

						<!-- search and acount -->
						<div class="col-sm-5 col-md-5 d-flex align-items-center justify-content-end" id="search_widget">
							<form method="get" action="#">

								<span role="status" aria-live="polite" class="ui-helper-hidden-accessible"></span>
								<input type="text" name="s" value="" placeholder="Search" class="ui-autocomplete-input" autocomplete="off">
								<button type="submit">
									<i class="fa fa-search"></i>
								</button>
							</form>

							<div id="block_myaccount_infos" class="hidden-sm-down dropdown">
								<div class="myaccount-title ">
									<a href="#acount" data-toggle="collapse" class="acount">
										<i class="fa fa-user" aria-hidden="true"></i>
										<span>Account</span>
										<i class="fa fa-angle-down" aria-hidden="true"></i>
									</a>
								</div>
								<div id="acount" class="collapse">
									<div class="account-list-content">
										<div>
											<a class="login" href="user-acount.html" rel="nofollow" title="Log in to your customer account">
												<i class="fa fa-cog"></i>
												<span>My Account</span>
											</a>
										</div>
										<div>
											<a class="login" href="user-login.html" rel="nofollow" title="Log in to your customer account">
												<i class="fa fa-sign-in"></i>
												<span>Sign in</span>
											</a>
										</div>
										<div>
											<a class="register" href="user-register.html" rel="nofollow" title="Register Account">
												<i class="fa fa-user"></i>
												<span>Register Account</span>
											</a>
										</div>
										<div>
											<a class="check-out" href="product-checkout.html" rel="nofollow" title="Checkout">
												<i class="fa fa-check" aria-hidden="true"></i>
												<span>Checkout</span>
											</a>
										</div>
										<div class="link_wishlist">
											<a href="user-wishlist.html" title="My Wishlists">
												<i class="fa fa-heart"></i>
												<span>My Wishlists</span>
											</a>
										</div>
										<div id="desktop_currency_selector" class="currency-selector groups-selector hidden-sm-down">
											<ul class="list-inline">
												<li>
													<a title="Euro" rel="nofollow" href="#">EUR</a>
												</li>
												<li class="current list-inline-item">
													<a title="British Pound Sterling" rel="nofollow" href="#">GBP</a>
												</li>
											</ul>
										</div>
										<div id="desktop_language_selector" class="language-selector groups-selector hidden-sm-down">
											<ul class="list-inline">
												<li class="list-inline-itemcurrent">
													<a href="#">
														<img class="img-fluid" src="{% static 'img/home/home1-flas.jpg' %}" alt="English" width="16" height="11">
													</a>
												</li>
												<li class="list-inline-item">
													<a href="#">
														<img class="img-fluid" src="{% static 'img/home/home1-flas2.jpg' %}" alt="Italiano" width="16" height="11">
													</a>
												</li>
												<li class="list-inline-item">
													<a href="#">
														<img class="img-fluid" src="{% static 'img/home/home1-flas3.jpg' %}" alt="Français" width="16" height="11">
													</a>
												</li>
												<li class="list-inline-item">
													<a href="#">
														<img class="img-fluid" src="{% static 'img/home/home1-flas4.jpg' %}" alt="Español" width="16" height="11">
													</a>
												</li>
											</ul>
										</div>
									</div>
								</div>
							</div>
							<div class="desktop_cart">
								<div class="blockcart block-cart cart-preview tiva-toggle">
									<div class="header-cart tiva-toggle-btn">
										<span class="cart-products-count">1</span>
										<i class="fa fa-shopping-cart" aria-hidden="true"></i>
									</div>
									<div class="dropdown-content">
										<div class="cart-content">
											<table>
												<tbody>
													<tr>
														<td class="product-image">
															<a href="product-detail.html">
																<img src="{% static 'img/product/5.jpg' %}" alt="Product">
															</a>
														</td>
														<td>
															<div class="product-name">
																<a href="product-detail.html">Organic Strawberry Fruits</a>
															</div>
															<div>
																2 x
																<span class="product-price">£28.98</span>
															</div>
														</td>
														<td class="action">
															<a class="remove" href="#">
																<i class="fa fa-trash-o" aria-hidden="true"></i>
															</a>
														</td>
													</tr>
													<tr class="total">
														<td colspan="2">Total:</td>
														<td>£92.96</td>
													</tr>

													<tr>
														<td colspan="3" class="d-flex justify-content-center">
															<div class="cart-button">
																<a href="product-cart.html" title="View Cart">View Cart</a>
																<a href="product-checkout.html" title="Checkout">Checkout</a>
															</div>
														</td>
													</tr>
												</tbody>
											</table>
										</div>
									</div>

								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</header>

templates/layout/header-home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>